#!/bin/bash

/bin/chmod -R 755 /Users/Shared/Ableton

# Power Settings
/usr/sbin/systemsetup -setsleep 90
/usr/sbin/systemsetup -setcomputersleep 105
/usr/sbin/systemsetup -setwakeonnetworkaccess on
/usr/sbin/systemsetup -setrestartpowerfailure on
/usr/bin/pmset -c disksleep 1
/usr/bin/pmset -c darkwakes 1
/usr/bin/pmset repeat restart weekdays 07:00:00

# Fix outset permissions
/bin/chown -R root:admin /usr/local/outset
/bin/chmod -R 755 /usr/local/outset

# Outset overrides
if [[ -f "/usr/local/outset/login-once/dock-set.sh" ]]; then
    /usr/local/outset/outset --add-override dock-set.sh
fi
if [[ -f "/usr/local/outset/login-once/account-setup.sh" ]]; then
    /usr/local/outset/outset --add-override account-setup.sh
fi