#!/bin/bash

/bin/chmod -R 755 /Users/Shared/Ableton

# Fix outset permissions
/bin/chown -R root:admin /usr/local/outset
/bin/chmod -R 755 /usr/local/outset

# Outset overrides
if [[ -f "/usr/local/outset/login-once/dock-set.sh" ]]; then
    /usr/local/outset/outset --add-override dock-set.sh
fi
if [[ -f "/usr/local/outset/login-once/account-setup.sh" ]]; then
    /usr/local/outset/outset --add-override account-setup.sh
fi
if [[ -f "/usr/local/outset/login-once/copy-logout-app.sh" ]]; then
    /usr/local/outset/outset --add-override copy-logout-app.sh
fi
if [[ -f "/usr/local/outset/login-once/reset-ableton.sh" ]]; then
    /usr/local/outset/outset --add-override reset-ableton.sh
fi

# Install Magic Wormhole
/usr/local/bin/python3 -m pip install magic-wormhole
echo "/Library/Frameworks/Python.framework/Versions/3.11/bin" > "/etc/paths.d/python3.11"

# Convert saltz and techsuite_admin into an admin
/usr/bin/dscl . -append /groups/admin GroupMembership techsuite_admin
/usr/bin/dscl . -append /groups/admin GroupMembership saltz