#!/bin/bash

chmod -R 0444 /Users/Shared/Ableton

# Power Settings
systemsetup -setsleep 15
systemsetup -setcomputersleep 30
pmset -c disksleep 1
systemsetup -setwakeonnetworkaccess on
systemsetup -setrestartpowerfailure on
pmset -c darkwakes 1
pmset repeat wakeorpoweron weekdays 07:00:00
pmset repeat shutdown weekdays 23:55:00

# Fix outset permissions
chown -R root:admin /usr/local/outset/
chmod -R 755 /usr/local/outset/

if [ ! -f /Users/Shared/.cr_flag ]; then

    mkdir -p "/Users/Shared/Dante Presets/"
    mkdir -p "/Users/Shared/Pro Tools I:O Configuration/"

elif [ ! -f /Users/Shared/.davis_flag ]; then

    mkdir -p "/Users/Shared/Dante Presets/"

elif [ ! -f /Users/Shared/.er_flag ]; then

    mkdir -p "/Users/Shared/Dante Presets/"

elif [ ! -f /Users/Shared/.mtl_flag ]; then

    :

fi

cd "/Library/Application Support/Tech Suite Deploy" || exit 1
git clone https://github.com/smtd-pat/techsuite-deploy