#!/bin/bash

chmod -R 0444 /Users/Shared/Ableton

# Power Settings
systemsetup -setsleep 15
systemsetup -setcomputersleep 30
pmset -c disksleep 1
systemsetup -setwakeonnetworkaccess on
systemsetup -setrestartpowerfailure on
pmset -c darkwakes 1
pmset repeat wakeorpoweron weekdays 07:00:00
pmset repeat shutdown weekdays 23:55:00

# Fix outset permissions
chown -R root:admin /usr/local/outset/
chmod -R 755 /usr/local/outset/

profiles -I -F "$RECEIPT_PATH/Tech Suite.mobileconfig"

if [ ! -f /Users/Shared/.cr_flag ]; then

    mkdir -p "/Users/Shared/Dante Presets/"
    mkdir -p "/Users/Shared/Pro Tools I:O Configuration/"
    yes | cp "$RECEIPT_PATH/docks/control-room/com.apple.dock.plist" "/Library/Preferences/com.apple.dock.plist"

elif [ ! -f /Users/Shared/.davis_flag ]; then

    mkdir -p "/Users/Shared/Dante Presets/"
    yes | cp "$RECEIPT_PATH/docks/davis/com.apple.dock.plist" "/Library/Preferences/com.apple.dock.plist"

elif [ ! -f /Users/Shared/.er_flag ]; then

    mkdir -p "/Users/Shared/Dante Presets/"
    yes | cp "$RECEIPT_PATH/docks/edit-rooms/com.apple.dock.plist" "/Library/Preferences/com.apple.dock.plist"

elif [ ! -f /Users/Shared/.mtl_flag ]; then

    yes | cp "$RECEIPT_PATH/docks/mtl/com.apple.dock.plist" "/Library/Preferences/com.apple.dock.plist"

fi

mkdir "/Shared/.ts-deploy"
cd "/Shared/.ts-deploy" || exit 1
git clone https://github.com/smtd-pat/techsuite-deploy