#!/bin/bash

chmod -R 0444 /Users/Shared/Ableton

# Power Settings
systemsetup -setsleep 15
systemsetup -setcomputersleep 30
pmset -c disksleep 1
systemsetup -setwakeonnetworkaccess on
systemsetup -setrestartpowerfailure on
pmset -c darkwakes 1
pmset repeat wakeorpoweron weekdays 07:00:00
pmset repeat shutdown weekdays 00:30:00

# Fix outset permissions
chown -R root:admin /usr/local/outset/
chmod -R 755 /usr/local/outset/

# profiles -I -F "$RECEIPT_PATH/Tech Suite MTL.mobileconfig"
# profiles -I -F "$RECEIPT_PATH/Tech Suite MTL Dock.mobileconfig"